#!/usr/bin/env python3
"""
Generate multiplication lookup tables sebagai Zig source code.

Index scheme: grid_i16[u8_bitcast(a)][u8_bitcast(b)] = a * b
dimana u8_bitcast(x) adalah representasi unsigned dari signed i8 x.

Contoh:
  a = -3 (i8) -> u8_bitcast = 253
  b = 4  (i8) -> u8_bitcast = 4
  grid_i16[253][4] = (-3) * 4 = -12
"""

import struct

def i8_to_u8(v):
    """Convert signed i8 [-128,127] to unsigned u8 [0,255] (bitcast)"""
    return v & 0xFF

def u8_to_i8(v):
    """Convert unsigned u8 [0,255] to signed i8 [-128,127] (bitcast)"""
    if v >= 128:
        return v - 256
    return v

def main():
    out_path = "src/lut_tables.zig"
    
    print(f"Generating LUT tables -> {out_path}")
    
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("//! ==========================================================\n")
        f.write("//! PRE-COMPUTED MULTIPLICATION TABLES\n")
        f.write("//! Generated by scripts/tools/gen_lut.py\n")
        f.write("//! DO NOT EDIT - regenerate with: python scripts/tools/gen_lut.py\n")
        f.write("//!\n")
        f.write("//! Index scheme: grid_i16[u8_bitcast(a)][u8_bitcast(b)] = a * b\n")
        f.write("//! where a, b are signed i8 values stored as u8 via @bitCast\n")
        f.write("//! ==========================================================\n\n")
        
        # ============================================================
        # Integer grid: raw_u8_index -> i8 * i8 result
        #
        # Index = u8 bitcast of i8 value:
        #   i8 value:  0,  1,  2, ..., 127, -128, -127, ..., -1
        #   u8 index:  0,  1,  2, ..., 127,  128,  129, ..., 255
        #
        # grid_i16[u8(a)][u8(b)] = i8(a) * i8(b)
        # ============================================================
        
        f.write("// Integer multiplication table: 256x256\n")
        f.write("// Index: grid_i16[@as(u8, @bitCast(a))][@as(u8, @bitCast(b))] = a * b\n")
        f.write("// where a, b are i8 values\n")
        f.write("// This allows direct indexing with raw u8 bytes from weight data\n")
        f.write("pub const grid_i16: [256][256]i16 align(64) = .{\n")
        
        for ua in range(256):
            a = u8_to_i8(ua)  # signed interpretation
            f.write("    .{ ")
            vals = []
            for ub in range(256):
                b = u8_to_i8(ub)  # signed interpretation
                product = a * b
                # Clamp to i16 range (max |127*128| = 16256, fits i16)
                vals.append(str(product))
            f.write(", ".join(vals))
            f.write(" },\n")
        
        f.write("};\n\n")
        
        # Verify a few values
        f.write("// Verification:\n")
        
        # 7 * 8 = 56: u8(7)=7, u8(8)=8 -> grid[7][8] = 56
        a, b = 7, 8
        f.write(f"//   {a} * {b} = {a*b}: grid[{i8_to_u8(a)}][{i8_to_u8(b)}]\n")
        
        # -3 * 4 = -12: u8(-3)=253, u8(4)=4 -> grid[253][4] = -12
        a, b = -3, 4
        f.write(f"//   {a} * {b} = {a*b}: grid[{i8_to_u8(a)}][{i8_to_u8(b)}]\n")
        
        # -5 * -6 = 30: u8(-5)=251, u8(-6)=250 -> grid[251][250] = 30
        a, b = -5, -6
        f.write(f"//   {a} * {b} = {a*b}: grid[{i8_to_u8(a)}][{i8_to_u8(b)}]\n")
        
        # 127 * 127 = 16129
        a, b = 127, 127
        f.write(f"//   {a} * {b} = {a*b}: grid[{i8_to_u8(a)}][{i8_to_u8(b)}]\n")
        
        # -128 * 127 = -16256
        a, b = -128, 127
        f.write(f"//   {a} * {b} = {a*b}: grid[{i8_to_u8(a)}][{i8_to_u8(b)}]\n")
        
        f.write("\n")
    
    total_kb = (256 * 256 * 2) / 1024
    print(f"Generated: {out_path}")
    print(f"  Integer grid: {total_kb:.0f} KB (i8 x i8 -> i16)")
    print(f"  Index scheme: raw u8 bitcast (no offset needed)")
    print()
    
    # Verify
    print("Verification:")
    tests = [(7, 8, 56), (-3, 4, -12), (-5, -6, 30), (127, 127, 16129), (-128, 127, -16256), (0, 50, 0), (-1, -1, 1)]
    for a, b, expected in tests:
        ua = i8_to_u8(a)
        ub = i8_to_u8(b)
        actual = u8_to_i8(ua) * u8_to_i8(ub)
        status = "OK" if actual == expected else "FAIL"
        print(f"  grid[{ua}][{ub}] = {a} * {b} = {actual} (expected {expected}) {status}")
    
    print("\nDone!")

if __name__ == "__main__":
    main()